##########################
### Yazi Configuration ###
##########################

[mgr]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
show_hidden = false
show_symlink = false

[preview]
wrap = "yes"

### Plugins ###
[plugin]
prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
]

prepend_previewers = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/vnd.rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/xz", run = "ouch" },
  { mime = "application/x-zstd", run = "ouch" },
  { mime = "application/zstd", run = "ouch" },
  { mime = "application/java-archive", run = "ouch" },
]

# For opening files with application #

[opener]

image_options = [
  { run = 'loupe "$@"', orphan = true, desc = "View in Loupe" },
  { run = 'gimp "$@"', orphan = true, desc = "Edit in GIMP" },
  { run = '$HOME/.local/bin/myScripts/wallpaperRelated/wallpaperSelect.sh --set "$@"', orphan = true, desc = "Set as Wallpaper" },
]

#video_options = [{ run = 'vlc "$@"', orphan = true, desc = "Open in VLC" }]

[open]
prepend_rules = [
  { name = "*.gif", use = [
    "image_options",
    "video_options",
  ] },
  { mime = "image/*", use = "image_options" },
]
